name: RaidableBases
version: '${project.version}'
main: net.resolutemc.raidablebases.RaidableBases
api-version: '1.20'
commands:
  RaidableBases:
    description: Default admin command
    permission: RaidableBases.Command.Admin
    aliases: rb
  ConsoleRaidableBases:
    description: Default console command
    aliases: crb